database:
  type: mysql
  dsn: "root:psyhygge@tcp(localhost:3306)/go_gateway?charset=utf8mb4&parseTime=True&loc=Local"
output:
  language: java # go java
  package_name: com.artist.gateway.entity
  file_model: entity # entity 或 mapper
  models_dir: ./output_models
  naming_style: PascalCase # camelCase 或 PascalCase
  file_naming_style: PascalCase # camelCase 或 snakeCase 或 PascalCase
  tables:   # 可选：指定要生成的表 为空则查询全部表
    - gateway_service_grpc_rule
    - gateway_service_access_control