database:
  type: mysql
  dsn: "root:123456@tcp(localhost:3306)/database?charset=utf8mb4&parseTime=True&loc=Local"
output:
  language: java # go java
  models_dir: ./output_models # 生成的文件存放目录
  naming_style: PascalCase # camelCase 或 PascalCase
  file_naming_style: camelCase # camelCase 或 snakeCase
  tables:   # 可选：指定要生成的表 为空则查询所有表
    - table_name
    - other_table_name